Change Slack links to Telegram links
hexlet-basics/exercises-python pull request #281
Opened 2023-03-09 13:46 UTC by danokp

2023-03-10 06:48 UTC, emp7yhead requested changes

2023-03-10 06:48 UTC, emp7yhead commented on drafts/10-basics/40-testing/description.en.yml
> +  However, if you are sure of an error or find some inaccuracy, you can always point it out. At the end of each theory, there is a link to the contents of the lesson on the githab (this project is co
Привет! Менять ссылки на англоязычных версиях нет необходимости.

2023-03-10 06:48 UTC, emp7yhead commented on modules/10-basics/40-testing/description.en.yml
> +  However, if you are sure of an error or find some inaccuracy, you can always point it out. At the end of each theory, there is a link to the contents of the lesson on the githab (this project is co
Ну и тут тоже

2023-03-10 08:41 UTC, danokp commented on drafts/10-basics/40-testing/description.en.yml
> +  However, if you are sure of an error or find some inaccuracy, you can always point it out. At the end of each theory, there is a link to the contents of the lesson on the githab (this project is co
Привет!
Я, видимо, не совсем правильно внес изменения и создал новый PR... Не очень понимаю, как его можно присоединить в этому PR.
https://github.com/hexlet-basics/exercises-python/pull/282

2023-03-13 04:40 UTC, emp7yhead commented
Этот ПР закрыл, второй принял. Спасибо!

2023-03-13 04:40 UTC, closed without merging